### ISSUE TITLE
Search Functionality

### ISSUE THREAD

**Issue by rrilling** [Gallery-Momiji/momiji-web#13]
Add the ability to search by either artist name, ID, piece number, piece name (Exact Name?)

**Comment by Mystro256** [comment]
Tiago has implemented a basic search functionality, this should work for now. Let me know if this works on your end.

**Comment by Mystro256** [comment]
FYI: I just added a "jump to artist" drop down as well as a search.

**Comment by rrilling** [comment]
Hi Jeremy,

I created a new ticket for it but the search bar looks like it is working well. The "Jump to artist" however doesn't seem to function

**Comment by Mystro256** [comment]
Closing this for now, we can test this weekend to make sure the jump works
