### ISSUE TITLE
Use randomly assigned bidder numbers.

### ISSUE THREAD

**Issue by rrilling** [Gallery-Momiji/momiji-web#15]
Hey Jeremy,

As we briefly talked about on Saturday do you think you can assign random bidder numbers instead of sequential numbers? Not really a high priority item but may help with people bidding as someone else

**Comment by Mystro256** [comment]
Fixed, but I made a SQL error in the table. By accident, I made the bidderno dataset too small. I will fix this in the setup script, you'll need to fix it on your test system by running this SQL query:
```mySQL
ALTER TABLE `bidders` CHANGE COLUMN `bidderno` `bidderno` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Unique Bidder No' AFTER `name`;
ALTER TABLE `bids` CHANGE COLUMN `bidderno` `bidderno` SMALLINT(3) UNSIGNED NOT NULL COMMENT 'Unique Bidder No' AFTER `value`;
```
Please let me know if this works for you with the latest code.

**Comment by Mystro256** [comment]
Closing as you said it looks good
