### ISSUE TITLE
Change button to say Live Auction?

### ISSUE THREAD

**Issue by rrilling** [Gallery-Momiji/momiji-web#16]
Hey would it possible to change the silent auction "select" button to "Live Auc!" or something else to identify quickly that it is going to live auction. That way users can quickly see if a piece is going to auction?

**Comment by Mystro256** [comment]
I'm not sure if we'll want this. I'll run it by the others.

**Comment by Mystro256** [comment]
I think we'll see how it goes this weekend, possibly change this next year if needed.
Thanks!

**Comment by Mystro256** [comment]
I'm going to close this as this adds quite a bit of overhead with little to gain.
A button label isn't very descriptive or straight forward.
Plus, I would rather people click and get invested rather than skip over the item.
