### ISSUE TITLE
What is the purpose my.cnf is

### ISSUE THREAD

**Issue by Mystro256** [Gallery-Momiji/momiji-web#2]
What is the value of this file?

**Comment by Mystro256** [comment]
Can config.php be merged into it?

**Comment by meaganhanes** [comment]
My guess is there's a reason it's a standalone file - perhaps the POS uses this file to link up with the database?

**Comment by Mystro256** [comment]
See if we can merge these, or make a script to dump the values of one into
another one. The simpler we can make it the better.

**Comment by medeirosT** [comment]
my.cnf is a MySQL service configuration file.

Probably left there as a default config for a working SQL environment.
