### ISSUE TITLE
Validation checks aren't complete

### ISSUE THREAD

**Issue by Mystro256** [Gallery-Momiji/momiji-web#6]
Does not check for valid:
-Email
-Phone Number
-Checkbox

**Comment by medeirosT** [comment]
Needs testing, see Commits:
- 6f0e806384af54299e75dcba6a6670a6888029ac
- ed92b8b44afc08cba52b51b52f46e5de4ce23327
- a399b218567aab93c2477eadf2515f16bd08ea6a
- e48a99c4f329a41b4cc51df309e64513607697f4

done in May 23rd, 2016

**Comment by Mystro256** [comment]
Can you modify the phone number to check these two rules instead of its current format method?

- Must contain at least 10 numbers
- Can only contain numbers, round brackets (), plus (+), minus/dash (-), spaces, periods, commas, or the letter "x" (upper or lower)

I don't really care how they format it, as long as it abides by those rules.

Thanks!

**Comment by Mystro256** [comment]
I tried to replicate this the best I can, although the "Must contain at least 10 numbers" seems difficult, without restricting format.

**Comment by Mystro256** [comment]
Marking as "good enough"
