### ISSUE TITLE
BidReg checkbox doesn't work

### ISSUE THREAD

**Issue by Mystro256** [Gallery-Momiji/momiji-web#7]
It seems that submitting with or without checking the term checkbox will always work.

This should only work when checked, tested using chrome.

**Comment by Mystro256** [comment]
I think this may be because the textarea also has the name/id "terms". Possibly tripping up the php script somehow? Oddly enough, `$value !== '1'` is always evaluated as false for some reason.

**Comment by medeirosT** [comment]
This was done rather quickly. so bugs are to occur :P I'll look into this first, as it is related to the app submitting with the checkbox not being pressed.

**Comment by Mystro256** [comment]
Thanks, note that I tweaked it a bit in the last commit for documentation purposes.

**Comment by Mystro256** [comment]
After looking into it, this seems to be the same issue as #6 , as none of the validation checks are working

I made a fix in js to disable the button if the checkbox isn't checked. I would prefer to still have the check in the php, but this works for now.
